import json
import logging
import requests
from flask import current_app

logger = logging.getLogger(__name__)

class AIServiceError(Exception):
    """Base exception for AI service failures."""
    pass

class AIConfigurationError(AIServiceError):
    """Raised when API key or model configuration is missing."""
    pass

def call_gemini(prompt: str, system_instruction: str = None) -> str:
    """
    Call Google Gemini REST API securely from backend.
    Never exposes API key to client.
    """
    api_key = current_app.config.get('GEMINI_API_KEY')
    if not api_key:
        raise AIConfigurationError(
            "Gemini API key is not configured. Please set GEMINI_API_KEY in your backend .env file to enable live AI Safety Planning."
        )

    model = current_app.config.get('GEMINI_MODEL', 'gemini-2.5-flash')
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"

    payload = {
        "contents": [
            {
                "parts": [
                    {"text": prompt}
                ]
            }
        ],
        "generationConfig": {
            "temperature": 0.3,
            "maxOutputTokens": 1024,
            "topP": 0.8
        }
    }

    if system_instruction:
        payload["systemInstruction"] = {
            "parts": [{"text": system_instruction}]
        }

    try:
        response = requests.post(
            url,
            headers={"Content-Type": "application/json"},
            data=json.dumps(payload),
            timeout=25
        )
    except requests.exceptions.Timeout:
        raise AIServiceError("The AI service request timed out. Please check your connection and try again.")
    except requests.exceptions.RequestException as e:
        logger.error(f"Network error calling Gemini: {e}")
        raise AIServiceError("Network error contacting the AI service. Please verify server internet access.")

    if response.status_code != 200:
        logger.error(f"Gemini API error ({response.status_code}): {response.text}")
        try:
            err_data = response.json()
            err_msg = err_data.get('error', {}).get('message', response.text)
        except Exception:
            err_msg = response.text
        raise AIServiceError(f"Gemini API request failed ({response.status_code}): {err_msg}")

    try:
        data = response.json()
        candidates = data.get('candidates', [])
        if not candidates:
            raise AIServiceError("No response generated by AI.")
        content = candidates[0].get('content', {})
        parts = content.get('parts', [])
        if not parts:
            raise AIServiceError("Empty response returned from AI.")
        return parts[0].get('text', '').strip()
    except Exception as e:
        if isinstance(e, AIServiceError):
            raise
        logger.error(f"Failed to parse Gemini response: {e}")
        raise AIServiceError("Unexpected format received from AI service.")
